(function() {var implementors = {};
implementors["riddle"] = [{"text":"impl&lt;'a&gt; Unpin for RiddleContext&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Unpin for RiddleLib","synthetic":true,"types":[]},{"text":"impl Unpin for RiddleState","synthetic":true,"types":[]},{"text":"impl Unpin for RiddleError","synthetic":true,"types":[]},{"text":"impl Unpin for Event","synthetic":true,"types":[]}];
implementors["riddle_audio"] = [{"text":"impl Unpin for AudioSystem","synthetic":true,"types":[]},{"text":"impl Unpin for AudioSystemHandle","synthetic":true,"types":[]},{"text":"impl Unpin for AudioSystemWeak","synthetic":true,"types":[]},{"text":"impl Unpin for Clip","synthetic":true,"types":[]},{"text":"impl Unpin for ClipPlayer","synthetic":true,"types":[]},{"text":"impl Unpin for ClipPlayerBuilder","synthetic":true,"types":[]},{"text":"impl Unpin for PlayMode","synthetic":true,"types":[]},{"text":"impl Unpin for AudioError","synthetic":true,"types":[]}];
implementors["riddle_common"] = [{"text":"impl&lt;E&gt; Unpin for Color&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: Unpin,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl Unpin for CommonError","synthetic":true,"types":[]},{"text":"impl&lt;T&gt; Unpin for EventPub&lt;T&gt;","synthetic":true,"types":[]},{"text":"impl&lt;T&gt; Unpin for EventSub&lt;T&gt;","synthetic":true,"types":[]}];
implementors["riddle_font"] = [{"text":"impl Unpin for TTFont","synthetic":true,"types":[]},{"text":"impl Unpin for FontError","synthetic":true,"types":[]}];
implementors["riddle_image"] = [{"text":"impl Unpin for Image","synthetic":true,"types":[]},{"text":"impl Unpin for ImageError","synthetic":true,"types":[]}];
implementors["riddle_input"] = [{"text":"impl Unpin for GamePadId","synthetic":true,"types":[]},{"text":"impl Unpin for InputSystem","synthetic":true,"types":[]},{"text":"impl Unpin for InputSystemHandle","synthetic":true,"types":[]},{"text":"impl Unpin for InputSystemWeak","synthetic":true,"types":[]},{"text":"impl Unpin for InputMainThreadState","synthetic":true,"types":[]},{"text":"impl Unpin for KeyboardModifiers","synthetic":true,"types":[]},{"text":"impl Unpin for InputError","synthetic":true,"types":[]},{"text":"impl Unpin for InputEvent","synthetic":true,"types":[]},{"text":"impl Unpin for GamePadButton","synthetic":true,"types":[]},{"text":"impl Unpin for GamePadAxis","synthetic":true,"types":[]}];
implementors["riddle_math"] = [{"text":"impl&lt;T&gt; Unpin for Rect&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Unpin,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl&lt;T&gt; Unpin for Vector2&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Unpin,&nbsp;</span>","synthetic":true,"types":[]}];
implementors["riddle_platform_common"] = [{"text":"impl Unpin for LogicalSize","synthetic":true,"types":[]},{"text":"impl Unpin for LogicalPosition","synthetic":true,"types":[]},{"text":"impl Unpin for LogicalVec2","synthetic":true,"types":[]},{"text":"impl Unpin for WindowId","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformEvent","synthetic":true,"types":[]},{"text":"impl Unpin for MouseButton","synthetic":true,"types":[]},{"text":"impl Unpin for Scancode","synthetic":true,"types":[]},{"text":"impl Unpin for VirtualKey","synthetic":true,"types":[]},{"text":"impl Unpin for MockWindow","synthetic":true,"types":[]}];
implementors["riddle_platform_winit"] = [{"text":"impl&lt;'a&gt; Unpin for PlatformContext&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformSystem","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformSystemHandle","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformSystemWeak","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformMainThreadState","synthetic":true,"types":[]},{"text":"impl Unpin for Window","synthetic":true,"types":[]},{"text":"impl Unpin for WindowHandle","synthetic":true,"types":[]},{"text":"impl Unpin for WindowWeak","synthetic":true,"types":[]},{"text":"impl Unpin for WindowBuilder","synthetic":true,"types":[]},{"text":"impl Unpin for PlatformError","synthetic":true,"types":[]}];
implementors["riddle_renderer_wgpu"] = [{"text":"impl Unpin for Renderer","synthetic":true,"types":[]},{"text":"impl Unpin for RendererHandle","synthetic":true,"types":[]},{"text":"impl Unpin for RendererWeak","synthetic":true,"types":[]},{"text":"impl Unpin for Sprite","synthetic":true,"types":[]},{"text":"impl Unpin for SpriteRenderCommand","synthetic":true,"types":[]},{"text":"impl Unpin for SpriteBuilder","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Unpin for SpriteAtlasBuilder&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Unpin for SpriteRenderTarget","synthetic":true,"types":[]},{"text":"impl Unpin for RendererError","synthetic":true,"types":[]},{"text":"impl Unpin for FilterMode","synthetic":true,"types":[]},{"text":"impl Unpin for WindowWGPUDevice","synthetic":true,"types":[]}];
implementors["riddle_time"] = [{"text":"impl Unpin for TimeSystem","synthetic":true,"types":[]},{"text":"impl Unpin for TimeSystemHandle","synthetic":true,"types":[]},{"text":"impl Unpin for TimeSystemWeak","synthetic":true,"types":[]},{"text":"impl Unpin for TimerHandle","synthetic":true,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()