var N = null;var sourcesIndex = {};
sourcesIndex["riddle"] = {"name":"","files":["context.rs","error.rs","event.rs","lib.rs","riddle_lib.rs","state.rs"]};
sourcesIndex["riddle_audio"] = {"name":"","dirs":[{"name":"ext","files":["audio_system.rs","mod.rs"]}],"files":["audio_system.rs","clip.rs","clip_player.rs","doctest.rs","error.rs","fades.rs","lib.rs"]};
sourcesIndex["riddle_common"] = {"name":"","files":["clone_handle.rs","color.rs","error.rs","eventpub.rs","lib.rs"]};
sourcesIndex["riddle_font"] = {"name":"","dirs":[{"name":"rusttype_ext","files":["mod.rs","ttfont.rs"]}],"files":["error.rs","lib.rs","ttfont.rs"]};
sourcesIndex["riddle_image"] = {"name":"","dirs":[{"name":"image_ext","files":["image.rs","mod.rs"]}],"files":["error.rs","image.rs","imageview.rs","lib.rs"]};
sourcesIndex["riddle_input"] = {"name":"","dirs":[{"name":"ext","files":["input_system.rs","mod.rs"]}],"files":["error.rs","event.rs","gamepad.rs","gamepad_state.rs","input_system.rs","keyboard_state.rs","lib.rs","mouse_state.rs"]};
sourcesIndex["riddle_math"] = {"name":"","files":["lib.rs","rect.rs","spacial_numeric.rs","vector.rs"]};
sourcesIndex["riddle_platform_common"] = {"name":"","dirs":[{"name":"traits","files":["mod.rs","window.rs"]}],"files":["dimensions.rs","doctest.rs","event.rs","lib.rs","mouse.rs","scancode.rs","virtualkey.rs","window_id.rs"]};
sourcesIndex["riddle_platform_winit"] = {"name":"","dirs":[{"name":"ext","files":["mod.rs","platform_system.rs"]},{"name":"winit_ext","files":["mod.rs","window.rs"]}],"files":["dimensions.rs","error.rs","event.rs","lib.rs","platform_context.rs","platform_system.rs","window.rs","window_map.rs"]};
sourcesIndex["riddle_renderer_wgpu"] = {"name":"","dirs":[{"name":"wgpu_ext","files":["buffered_renderer.rs","device.rs","mod.rs","render_context.rs","renderable.rs","renderer.rs","shader.rs","sprite.rs","sprite_atlas.rs","sprite_render_target.rs","swap_chain_target.rs","target.rs","texture.rs","vertex.rs","window_device.rs"]}],"files":["error.rs","lib.rs","sprite_utils.rs"]};
sourcesIndex["riddle_time"] = {"name":"","dirs":[{"name":"ext","files":["mod.rs","time_system.rs"]}],"files":["doctest.rs","lib.rs","time_system.rs","timer.rs"]};
createSourceSidebar();
