(function() {var implementors = {};
implementors["riddle"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle/enum.RiddleError.html\" title=\"enum riddle::RiddleError\">RiddleError</a>","synthetic":false,"types":["riddle::error::RiddleError"]}];
implementors["riddle_audio"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_audio/enum.AudioError.html\" title=\"enum riddle_audio::AudioError\">AudioError</a>","synthetic":false,"types":["riddle_audio::error::AudioError"]}];
implementors["riddle_common"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_common/enum.CommonError.html\" title=\"enum riddle_common::CommonError\">CommonError</a>","synthetic":false,"types":["riddle_common::error::CommonError"]}];
implementors["riddle_font"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_font/enum.FontError.html\" title=\"enum riddle_font::FontError\">FontError</a>","synthetic":false,"types":["riddle_font::error::FontError"]}];
implementors["riddle_image"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_image/enum.ImageError.html\" title=\"enum riddle_image::ImageError\">ImageError</a>","synthetic":false,"types":["riddle_image::error::ImageError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_image/packer/enum.ImagePackerError.html\" title=\"enum riddle_image::packer::ImagePackerError\">ImagePackerError</a>","synthetic":false,"types":["riddle_image::packer::ImagePackerError"]}];
implementors["riddle_input"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_input/enum.InputError.html\" title=\"enum riddle_input::InputError\">InputError</a>","synthetic":false,"types":["riddle_input::error::InputError"]}];
implementors["riddle_platform_winit"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_platform_winit/enum.PlatformError.html\" title=\"enum riddle_platform_winit::PlatformError\">PlatformError</a>","synthetic":false,"types":["riddle_platform_winit::error::PlatformError"]}];
implementors["riddle_renderer_common"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_renderer_common/enum.RendererError.html\" title=\"enum riddle_renderer_common::RendererError\">RendererError</a>","synthetic":false,"types":["riddle_renderer_common::RendererError"]}];
implementors["riddle_renderer_wgpu"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"riddle_renderer_wgpu/enum.WGPURendererError.html\" title=\"enum riddle_renderer_wgpu::WGPURendererError\">WGPURendererError</a>","synthetic":false,"types":["riddle_renderer_wgpu::error::WGPURendererError"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()